### ISSUE TITLE
Include SuperJSON tRPC transformer

### ISSUE THREAD

**Issue by TheoBr** [nexxeln/create-t3-app#1]
Big fan of the SuperJSON tRPC transformer, lets you send/receive p much anything from tRPC

I can file a PR next week maybe but happy to take a look at it if someone else takes it 👀 

https://trpc.io/docs/data-transformers#using-superjson

**Comment by nexxeln** [comment]
I'll try to do this. If I get stuck please help me lol.

**Comment by nexxeln** [comment]
Resolved. Please check this commit: 1c278b5c8e2a19980f516e87874ea63bc058c43a.

Is this correct?

**Comment by TheoBr** [comment]
Looks perfect to me!
