### ISSUE TITLE
Add default project name

### ISSUE THREAD

**Issue by anthonylaflamme** [nexxeln/create-t3-app#11]
Enhancement

Add a default project name on prompt so I can just enter and proceed to next step

**Comment by anthonylaflamme** [comment]
This can also resolve empty project name prompt that resolve in an issue : 
<img width="454" alt="Screen Shot 2022-06-17 at 3 48 55 PM" src="https://user-images.githubusercontent.com/4626172/174392238-53c43813-1856-46d5-b067-b117ea7cba6d.png">

**Comment by mallsjr** [comment]
I believe I have a fix for this. What would be a good default project name?

**Comment by nexxeln** [comment]
> I believe I have a fix for this. What would be a good default project name?

t3-app would be a nice default name imo.

**Comment by nexxeln** [comment]
implemented in #19
