### ISSUE TITLE
Add console log telling me where i'm scaffolding

### ISSUE THREAD

**Issue by anthonylaflamme** [nexxeln/create-t3-app#13]
Enhancement: 

Add a log telling me where im scaffolding

if I create a new project named:  test-project in /workspace

Return before "using: yarn" : 

"Scaffolding in /Users/John/workspace/test-project"

**Comment by nexxeln** [comment]
Thank you for opening these issues, would you be willing to contribute to fix some of these?

**Comment by anthonylaflamme** [comment]
I sure can try

I’ll see if I have time this week end or i’ll try next week

Anthony Laflamme
