### ISSUE TITLE
Doesn't show correct package manager in the install prompt

### ISSUE THREAD

**Issue by nexxeln** [nexxeln/create-t3-app#152]
**Describe the bug**
While using the cli, in the installation prompt it doesn't say the package manager the user is using, but if you say yes, it actually doesn't use npm and uses the correct package manager.
**To Reproduce**

1. Run this `pnpm dlx create-t3-app@5.0.0-beta.5`
2. The fourth prompt will say `Would you like us to run npm install?` instead of `pnpm`

**Expected behavior**
It should mention the correct package manager in the prompt.
**Screenshots**
![ss](https://us-east-1.tixte.net/uploads/nexxel.needs.rest/WindowsTerminal_TVemowuw3b.png)

**Comment by juliusmarminge** [comment]
Yeah probably. I guess just a call to getPackageManager() would do?

? Would you like us to run ${getPackageManager()} install?

**Comment by juliusmarminge** [comment]
Oh sorry didnt update before i pressed send
