### ISSUE TITLE
feat: adding Lucia for Authentication

### ISSUE THREAD

**Issue by SooditK** [nexxeln/create-t3-app#1606]
### Is your feature request related to a problem? Please describe.

not a problem, but it would be great to have another selection for [Lucia](https://lucia-auth.com/)
users would be able to choose between Auth.js/Lucia for handling their Auth

### Describe the solution you'd like to see

a option to select from either Lucia or Auth.js (NextAuth.js)

### Describe alternate solutions

N/A

### Additional information

I would be happy to do it 😃

**Comment by ronanru** [comment]
We are already talking about it in #1593

**Comment by SooditK** [comment]
I saw your repository for Lucia + Drizzle, I would've done the same thing, great work 👍🏼
