### ISSUE TITLE
install each package separately

### ISSUE THREAD

**Issue by juliusmarminge** [nexxeln/create-t3-app#18]
as discussed in #15, I have started playing around with the thought of having each package installed separately and thus not requiring to build templates for every possible package-combination.

current progress can be found [here](https://github.com/juliusmarminge/create-t3-app/tree/individual-installs)

feedback is welcome

**Comment by nexxeln** [comment]
this is also being discussed in #19

**Comment by TheoBr** [comment]
IMO this is the only viable path to make create-t3-app both as dynamic and maintainable as we hope to.

> this practice is rarely used across scaffolding techniques
I'm not sure @anthonylaflamme, I understand why Vite doesn't (most of their examples aren't even based in the same frameworks), but I'd be surprised if this was the case for other options.

How does Remix do their stacks thing? 👀

**Comment by nexxeln** [comment]
implemented in #19

**Comment by anthonylaflamme** [comment]
@TheoBr the approach taken was definitely the right one ! You are right
