### ISSUE TITLE
Questions - additional meta framework options

### ISSUE THREAD

**Issue by default-kaas** [nexxeln/create-t3-app#213]
Would it be possible to add Nuxt and Sveltekit as alternatives to Next?

Or does Trpc only work fully with Next?

And does Trpc v10 work well with Nuxt and Sveltekit?

**Comment by default-kaas** [comment]
Should this be added to the - FAQ issue?

**Comment by nexxeln** [comment]
Nuxt already has a nice trpc like thing built in -> [docs link](https://v3.nuxtjs.org/guide/features/data-fetching/). As for SvelteKit, there are no plans as of yet and it is definitely very unlikely. Maybe if React becomes unusable :o

**Comment by nexxeln** [comment]
> Should this be added to the - "FAQ for the common BS" issue?

Probably

**Comment by default-kaas** [comment]
> > Should this be added to the - "FAQ for the common BS" issue?
> 
> Probably

Should I added it for noobs like me?
