### ISSUE TITLE
Erroneously selects yarn just because I have it installed

### ISSUE THREAD

**Issue by TheoBr** [nexxeln/create-t3-app#22]
I have Yarn installed for mostly react native stuff, for some reason create-t3-app always picks it. Would love to be able to pick between yarn, npm and pnpm, but would be cool with it auto-selecting which I "ran it with" as well

**Comment by nexxeln** [comment]
Yeah looks like https://github.com/nexxeln/create-t3-app/blob/main/src/helpers/get-pkg-manager.ts is very buggy, I'll rewrite this.

**Comment by nexxeln** [comment]
Fixed in #30
