### ISSUE TITLE
Prettier?

### ISSUE THREAD

**Issue by TheoBr** [nexxeln/create-t3-app#25]
🤔

**Comment by nexxeln** [comment]
Yeah we could have a config but I think that may be too opinionated? I personally just use the default that comes with the vscode extension. If someone wants prettier they can install/configure it themselves imo. What do you think?

**Comment by booleans-oss** [comment]
Make it optional ? When generating a project, it prompts whether to add a prettier config file and packages or not.

**Comment by TheoBr** [comment]
Thought a bit about this and I don't think it meaningfully differs from my stance on "add Jotai/Zustand"

You can just NPM install if you want prettier. No need for us to include. I think I let my desire for prettier get ahead of me 😂

**Comment by nexxeln** [comment]
I think that most people have prettier installed in their editor and if they have a preferred config then can do that on their own. Closing this now after discussing on discord.
