### ISSUE TITLE
Add Options for Tailwind Plugins

### ISSUE THREAD

**Issue by Dax911** [nexxeln/create-t3-app#36]
I love tailwind but I am not a fan of full react component style libraries.  Tailwind plugins are the perfect middle ground.  (DaisyUI etc)

**Comment by juliusmarminge** [comment]
This is a very trivial thing to setup, just `npm install daisyui` and `require(daisyui)` under tailwind plugins. The aim of this CLI is to setup annoying boilerplate and I don't think this would qualify as that.

**Comment by nexxeln** [comment]
Agree with @juliusmarminge here.
