### ISSUE TITLE
option to provide project name as argv

### ISSUE THREAD

**Issue by juliusmarminge** [nexxeln/create-t3-app#37]
Many CLI's allows you to include your name as a command-line-argument (argv), e.g. `npm create-turbo <project_name>`. It would be nice to support this too.

- If name is provided as argv, that should be used and the name-prompt be skipped. 
- If no name is provided, the prompt should be displayed.

**Comment by nexxeln** [comment]
Yeah we could implement this, shouldn't be too hard.

**Comment by MWhite-22** [comment]
We should think about adding in a --noGit and --noInstall flag (or cli options) as well. 

In a future when the t3 stack is used to spin up a new app inside of an already existing monorepo, having the app create its own git and node_modules would just require the end user to then go in and delete those folders before reinstalling node_modules at their monorepo root.

**Comment by juliusmarminge** [comment]
I was actually doing this yesterday and thought that would be cool to have

**Comment by MWhite-22** [comment]
Anyone currently tackling this? 

@asheeeshh You mentioned in the discord you were interested? LMK if not and i'll dive right in

**Comment by nexxeln** [comment]
@asheeeshh has some technical issues with his keyboard. So feel free @MWhite-22!

**Comment by MWhite-22** [comment]
This should be ready to go today. I had to do some pretty decent refactoring to support a --noInstall flag

**Comment by nexxeln** [comment]
Great! You might have some merge conflicts tho because I just merged #47.

**Comment by MWhite-22** [comment]
I'll work through that before pushing up to GH

**Comment by MWhite-22** [comment]
This is completed in 4.1 and can be closed
