### ISSUE TITLE
Moving the "useX" questions into a select prompt, rather than individual questions

### ISSUE THREAD

**Issue by MWhite-22** [nexxeln/create-t3-app#42]
I think moving the "useTailwind", "useTrpc", etc., questions into a select block is a better UX for those that want to see all the options available before selecting.

**Comment by juliusmarminge** [comment]
There is a multiselect example from a previous PR here: https://github.com/nexxeln/create-t3-app/commit/ead9ea84e36634eb1f2c3c5d5efd1cde5c8580e2
