### ISSUE TITLE
bug: docs table of contents scroll behavior

### ISSUE THREAD

**Issue by c-ehrlich** [nexxeln/create-t3-app#525]
### Provide environment information

MacBook Air 13", default screen scaling

### Describe the bug

On long pages, it's not possible to see the bottom of the table of contents without scrolling to the bottom of the page first

https://user-images.githubusercontent.com/8353666/193279657-81e399d6-1a28-42ff-aa09-ff5763cd6bd9.mov

### To reproduce

Go to https://create-t3-app-nu.vercel.app/en/deployment/docker on a laptop size screen, and try to scroll to the bottom of the table of contents

**Comment by nexxeln** [comment]
Yeah I've noticed this too. Not sure how to fix it tho.
