### ISSUE TITLE
Update package to conform to ESM standards

### ISSUE THREAD

**Issue by MWhite-22** [nexxeln/create-t3-app#53]
I feel like this is probably a good idea. Especially as some of the packages we are using have already moved to pure ESM and we need to peg to an older version to continue using them.

Having TSUP #43 already merged makes this a lot easier too.

Thoughts?

**Comment by nexxeln** [comment]
Yeah I hadn't noticed we were compiling to CJS before we got errors from latest version of ora which is ESM only. Huge mistake on my part. I tried changing the tsconfig to compile to ESM but then it was breaking other stuff so I just left it. If you can make it work with ESM that would be great. Then we could use the latest version of ora as well.
