### ISSUE TITLE
feat: Query Cache

### ISSUE THREAD

**Issue by oyavuzjr** [nexxeln/create-t3-app#586]
### Is your feature request related to a problem? Please describe.

I am using trpc to fetch some data in a number of different pages.
- pages
    - home.tsx
    - posts.tsx

```
function Posts(){
    const { isSuccess, data } = trpc.useQuery(['post.get-posts']);
    return (
        <>{JSON.stringify(data)}</>
    )
}
```

This works fine but when I change pages and come back the data is once again in a loading state.
The cache thats supposed to be there from react query doesn't seem to do its job. I am not sure if this is because using pages with next js is not a spa approach and the cache is somehow reset.

### Describe the solution you'd like to see

The expected behaviour is that the data would still be fetched but the stale data would be visible on page load from whats stored in the query cache. 

### Desribe alternate solutions

I am not sure if using the context API would be a solution to this
The context could wrap a hypothetical dashboard root and provide the data to the different pages.
- pages
    - Dashboard
        - home.tsx
        - posts.tsx

If it comes down to it this is the method I will attempt, but I would prefer if the query has a way to retain the cache throughout different pages. I am not sure what are the implications of using react query in nextjs/T3/trpc I wanted to know if there is an easy solution I am missing
Thank you

**Comment by c-ehrlich** [comment]
The QueryCache is enabled by default. See a minimal demonstration here: https://github.com/c-ehrlich/t3-caching-demo

**Comment by oleksandr-danylchenko** [comment]
@oyavuzjr, I'm having the same issue. All queries are always re-fetching on every re-render. Only setting `staleTime` to a high number helps. Did you find a better solution?

**Comment by oleksandr-danylchenko** [comment]
UPD:

> Query instances via useQuery or useInfiniteQuery by default consider cached data as stale

See - https://tanstack.com/query/v4/docs/react/guides/important-defaults. By default React Query treats all the queries as state and will try to re-fetch them asap.
But when you wanna avoid that you can increase the `staleTime` for the query. See this article for more details - https://www.codemzy.com/blog/react-query-cachetime-staletime
And if you wanna update `QueryClient` config globally you can do in in the `config` method within the `createTRPCNext`:
```typescript
export const api = createTRPCNext<AppRouter>({
  config() {
    return {
      ...
      /**
       * Query client configuration
       * @see https://tanstack.com/query/v4/docs/react/reference/QueryClient
       */
      queryClientConfig: {
        defaultOptions: {
          queries: {
            staleTime: 1000 * 60 * 5, // 5 minutes
            cacheTime: 1000 * 60 * 10, // 10 minutes
          },
        },
      }
      ...
    }
});
```

**Comment by acharlop** [comment]
`queryClientConfig` is not a valid argument though.
