### ISSUE TITLE
pretty print title and welcome message

### ISSUE THREAD

**Issue by juliusmarminge** [nexxeln/create-t3-app#60]
**Is your feature request related to a problem? Please describe.**
The current welcome message looks a bit like an error. I suggest adjusting the styles to make it more "welcoming".
<img width="722" alt="CleanShot 2022-06-27 at 21 55 39@2x" src="https://user-images.githubusercontent.com/51714798/176024688-15fe00c3-061a-4313-8e5e-d434cf280a8d.png">

**Describe the solution you'd like**
For example, the CLI for initializing a turborepo looks like this:
<img width="804" alt="CleanShot 2022-06-27 at 21 49 53@2x" src="https://user-images.githubusercontent.com/51714798/176024286-1283f158-5902-48fb-9925-f4a4061e7385.png">

**Describe alternatives you've considered**
The chosen styling is absolutely up for debate to fit the t3 theme and the proposed new logo 
<img src="https://cdn.discordapp.com/attachments/988912020558602331/991021647882489926/t3-bad-logo.jpg" width="200"/>

**Comment by juliusmarminge** [comment]
<img width="484" alt="CleanShot 2022-06-27 at 23 58 32@2x" src="https://user-images.githubusercontent.com/51714798/176042885-202762b1-8e9a-48b7-88cc-dbf5d7f7853c.png">

an initial proposal, thoughts?

**Comment by MWhite-22** [comment]
As much as I like TurboRepos style, I want to see if we can come up with our own flair. 

Nothing over the top, but a tiny touch of unique design style could bring a cohesive experience to the whole scaffolding process.

**Comment by asheeeshh** [comment]
t3 ascii art with gradient?

**Comment by Dhravya** [comment]
I like the idea of a [figlet](https://en.wikipedia.org/wiki/FIGlet) with gradient background.
I recently came across this style too. It won't look good here and probably too big, but maybe some variation of it
![image](https://user-images.githubusercontent.com/63950637/176088427-bc0cd05f-9b7c-4489-8871-45ad2dbe3563.png)


How do they make these?

**Comment by asheeeshh** [comment]
> I like the idea of a [figlet](https://en.wikipedia.org/wiki/FIGlet) with gradient background. I recently came across this style too. It won't look good here and probably too big, but maybe some variation of it ![image](https://user-images.githubusercontent.com/63950637/176088427-bc0cd05f-9b7c-4489-8871-45ad2dbe3563.png)
> 
> How do they make these?

i think its available in figlet

moreover `chalk-animation` doesn't work for now due to the same compiling to cjs issue, will need to wait for #61 to get merged

**Comment by juliusmarminge** [comment]
<img width="422" alt="CleanShot 2022-06-28 at 10 26 31@2x" src="https://user-images.githubusercontent.com/51714798/176131754-03ce6b2f-33d3-4aa9-981d-9096ea966821.png">

ascii art title with gradient text?

**Comment by fdemir** [comment]
ascii looks cool and clean.

**Comment by nexxeln** [comment]
I would love some chalk animations tbh. But if that doesn't work out ascii would be really cool too.

**Comment by juliusmarminge** [comment]
Let me look into animations.

What sort of animation are you thinking about? Colors or textwriter?

**Comment by nexxeln** [comment]
I think the rainbow or neon animation from this library looks good. https://github.com/bokub/chalk-animation

What do you think?

**Comment by juliusmarminge** [comment]
Not a fan of the rainbow colors but if the animation can use custom colors perhaps use some purple tones to go along with the logo?

**Comment by nexxeln** [comment]
Poimandres theme would be nice, not sure if we can use custom colours though.

**Comment by MWhite-22** [comment]
I think one thing to be aware of with command line animations is that as soon as the user interacts as goes to the next question, the animation stops

**Comment by juliusmarminge** [comment]
> I think one thing to be aware of with command line animations is that as soon as the user interacts as goes to the next question, the animation stops

As it stands I can't even get the first question when animating...

![CleanShot 2022-06-28 at 13 58 31](https://user-images.githubusercontent.com/51714798/176173161-a8e4fa5f-a235-4bdf-bd95-0f5d50447572.gif)

**Comment by MWhite-22** [comment]
Pressing enter or any other key doesn't progress forward?

**Comment by juliusmarminge** [comment]
> Pressing enter or any other key doesn't progress forward?

Sure but it's not a very good UX:
![CleanShot 2022-06-28 at 14 02 04](https://user-images.githubusercontent.com/51714798/176173795-2f5b4ff9-9c4c-4c5c-a8ed-f1f0d5a7e1ac.gif)
