### ISSUE TITLE
Adding in templates for a react native monorepo?

### ISSUE THREAD

**Issue by MWhite-22** [nexxeln/create-t3-app#69]
Thinking of new features we can push to enhance the cli, one that keeps popping up in discord is the ability to have tRPC in a monorepo with react native. 

Should we have an option to emulate a structure like in [zart](https://github.com/KATT/zart)?

**Comment by juliusmarminge** [comment]
I have a [starter repo](https://github.com/juliusmarminge/turbo-expo-next-starter) on the way for this.

Not quite ready yet (feel free to check it out and make changes) but could potentially be merged with the CLI at a later stage if requested.

**Comment by alonzuman** [comment]
Theres also KATTs starter (creator of trpc) for this

https://github.com/KATT/zart

**Comment by nexxeln** [comment]
I'll close this issue now.
