### ISSUE TITLE
What about docker file?

### ISSUE THREAD

**Issue by gkio** [nexxeln/create-t3-app#78]
Some devs pref use docker env in local machines. what about to add Docker option with (trpc, tailwind, etc) ?

**Comment by nexxeln** [comment]
We could do this, I would like other people's opinion on this too.

**Comment by Dhravya** [comment]
I mean, the CLI itself would run just fine *inside* a dockerfile

I'm not sure why someone would build a CLI image... Any particular reason?

**Comment by asheeeshh** [comment]
if you're talking about including dockerfile in the template then it makes somewhat sense, but i dont think creating docker image of the cli itself is a good idea as @Dhravya said

**Comment by gkio** [comment]
not the cli but include in template dockerfile of the project it self not the cli

**Comment by nexxeln** [comment]
We are gonna add a prompt for docker. Weskey on discord is working on this.

**Comment by matt123miller** [comment]
I would find value from this

**Comment by MWhite-22** [comment]
So we should probably do via conditional logic. 

If the user selects prisma from the CLI options, prompt them with a new question:

Which DB would you like to use:
- Sqlite (Local Dev Only) [Default]
- Docker-Compose (Mysql)
- Docker-Compose (Postgres)

**Comment by bu3alwa** [comment]
I think this is far off from the project goal in my view. The cli is a quick start for having packages of the stack to get you coding as fast as possible. Docker is a separate system with many having different preferences on what container to use and how to setup their dev environment. I think that should be left to the user to decide their dev and deployment method.

**Comment by nexxeln** [comment]
> I think this is far off from the project goal in my view. The cli is a quick start for having packages of the stack to get you coding as fast as possible. Docker is a separate system with many having different preferences on what container to use and how to setup their dev environment. I think that should be left to the user to decide their dev and deployment method.

I tend to agree here.

**Comment by TheoBr** [comment]
Please do not do this

**Comment by nexxeln** [comment]
Alright I will close this now.
