### ISSUE TITLE
Mantine templating

### ISSUE THREAD

**Issue by spigelli** [nexxeln/create-t3-app#79]
I tend to use [mantine](mantine.dev) for all my projects, I've got a template based on the mantine next template that's got some pages for next auth too.
How would everyone feel if there was an option for that as an alternative to the base pages and tailwind.

Maybe you could isolate the mantine styles api as an option as well 🤔

**Comment by nexxeln** [comment]
I love mantine too, its not really t3 stack though. So we won't be adding this to the template.

While selecting the packages you can exclude tailwind and scaffold the base template with whatever you need (tRPC, Prisma, etc), and then install and setup mantine yourself.
